// Package audit carries the files this repository publishes as data: the
// framework profiles, the proto and its generated JSON Schema, and the
// binaries' configuration schemas. The meta-schemas and the common catalogue are the SDK's (github.com/truvity/sluis/audit/sdk).
//
// They are embedded so that a deployment gets them from the binary it already
// runs, rather than from files it has to ship and keep in step.
package audit

import "embed"

// Profiles are the framework profiles under profiles/.
//
//go:embed profiles/*.yaml
var Profiles embed.FS

// Proto is the schema of record itself. The writer copies the proto of a
// record's major beside the record's JSON Schema on first use, so the archive
// keeps the meaning of every field and not only its shape.
//
//go:embed proto/audit/v1/*.proto
var Proto embed.FS

// Generated holds what this build published for readers outside Go: the
// record's JSON Schema, with the proto's comments carried as descriptions. The
// writer puts a copy of it in the archive beside the records it describes.
//
//go:embed gen/jsonschema/*.json
var Generated embed.FS

// ConfigSchemas are the schemas of each binary's configuration file, under
// schemas/config/. They are generated by `just config-schemas` from
// internal/config and committed, so that a deployment can validate its file
// without this repository's code. Version 1 of each is kept under
// schemas/config/v1/, for the one minor in which it is still read.
//
//go:embed schemas/config/*.schema.json schemas/config/v1/*.schema.json
var ConfigSchemas embed.FS
