package auditpulumi

import (
	"errors"
	"fmt"
	"net/url"
	"regexp"
	"strings"

	"github.com/pulumi/pulumi-aws/sdk/v7/go/aws/kms"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"

	"github.com/truvity/sluis/audit/profile"
)

// KeysArgs are the keys of the installation, by purpose, named by KMS alias.
//
// The library creates no key. A key is the estate's: it outlives an
// installation, it is administered by whoever holds the estate's key policy, and
// destroying one makes everything under it unreadable or unverifiable, which is
// not a thing a stack's destroy should be able to do. The estate creates the
// key and its alias, with a key policy that lets the installation's roles use
// it (SealKeyPolicy is the seal key's), and the library resolves each alias
// with kms.LookupAlias to the key's ARN, which is what an IAM policy can name,
// and grants the roles the actions they need on it. The aliases are what the
// functions' configuration names (keys.seal, keys.pseudonym, keys.conceal,
// archive.kmsKey), as the storage port (github.com/truvity/sluis/storage/keys)
// reads them.
//
// An alias is `alias/<name>`: an ARN or a key id is refused, so that a key can
// be replaced by re-pointing its alias without editing the installation.
type KeysArgs struct {
	// Archive is the key the archive's objects are encrypted with (SSE-KMS):
	// the writer, the notary and the readers are granted GenerateDataKey and
	// Decrypt on it. It is the key of every AWS preset that names no KeyAlias of its
	// own. Required with Archive.Encryption "kms" (the default) for a bucket the
	// library creates that names none, unless Archive.KeyArn is given; refused
	// otherwise, and when every preset is at an endpoint. The grant has no encryption-context
	// condition: S3 binds its own context (the object's bucket), not the port's.
	Archive string
	// Seal is the P-384 key seals are signed with, SIGN_VERIFY (ES384). Required
	// when there is a notary; refused without one. Only the notary's role is
	// granted Sign on it, and a signature takes no encryption context.
	Seal string
	// Pseudonym is the key the per-tenant pseudonym secrets are wrapped under. It
	// is provisioned only for an installation that pseudonymises: the attested
	// preset, or a profile that replaces an identity with a pseudonym; with
	// neither it is refused, naming the preset. Only the writer is granted
	// GenerateDataKey and Decrypt on it, conditioned on the encryption context
	// purpose=pseudonym.
	Pseudonym string
	// Conceal is the key identities are sealed under, for the cases the law
	// requires them to be recoverable. Same condition as Pseudonym. The writer is
	// granted Encrypt, Decrypt and GenerateDataKey on it, conditioned on the
	// encryption context the storage KMS backend sends: instance and purpose.
	Conceal string
	// Instance names the installation in that context ({instance, purpose}).
	// Default the name the component is registered under. It is bound into
	// ciphertexts: choose it once.
	Instance string
}

// StateArgs is the installation's state store: the SSM parameters the library
// and the functions keep for themselves, under Root. What is internal is under
// Root/internal/: the archive's credentials (Root/internal/archive) and the
// per-tenant secrets behind pseudonyms (Root/internal/pseudonym/...). The
// functions read and write them through github.com/truvity/sluis/storage/state.
//
// The library creates no parameter whose value is a secret: it would be in the
// stack's state. The credentials are written by the operator, once
// (docs/guides/audit/operate/archive-on-r2.md); the pseudonym secrets are generated by the
// writer and are ciphertext under the pseudonym key.
type StateArgs struct {
	// Root is the parameter path of the installation, without a trailing slash,
	// under /audit/ like Writer.Secrets.Root. Default `/audit/<name>`.
	Root string
	// KeyArn is the customer-managed KMS key the SecureStrings are encrypted
	// with. The roles are granted Decrypt (and, for what they write,
	// GenerateDataKey) on it through SSM only. Empty means the AWS-managed key
	// `alias/aws/ssm`, which needs no grant.
	KeyArn string
}

var aliasRE = regexp.MustCompile(`^alias/[a-zA-Z0-9/_-]+$`)

// checkAlias refuses what the storage port refuses: an ARN, a key id, an AWS
// managed alias.
func checkAlias(field, alias string) error {
	switch {
	case strings.HasPrefix(alias, "arn:"):
		return fmt.Errorf("auditpulumi: %s %q is an ARN: name the key by alias (alias/<name>), so the key can be replaced "+
			"without editing the installation", field, alias)
	case strings.HasPrefix(alias, "alias/aws/"):
		return fmt.Errorf("auditpulumi: %s %q is an AWS managed alias, whose key policy cannot be your own: create a "+
			"customer managed key and alias it", field, alias)
	case !aliasRE.MatchString(alias):
		return fmt.Errorf("auditpulumi: %s %q must be a KMS alias: alias/ followed by letters, digits, '/', '_' or '-'", field, alias)
	}
	return nil
}

// checkKeys holds Keys to the configured presets and the profiles: which
// purposes the installation provisions, and which it must be given.
func (a *Args) checkKeys() error {
	k := &a.Keys
	for field, alias := range map[string]string{
		"Keys.Archive": k.Archive, "Keys.Seal": k.Seal, "Keys.Pseudonym": k.Pseudonym, "Keys.Conceal": k.Conceal,
	} {
		if alias == "" {
			continue
		}
		if err := checkAlias(field, alias); err != nil {
			return err
		}
	}
	if k.Instance != "" && !instanceRE.MatchString(k.Instance) {
		return fmt.Errorf("auditpulumi: Keys.Instance %q must be letters, digits, . _ and - (it is bound into ciphertexts)", k.Instance)
	}
	f := a.features
	switch {
	case k.Seal != "" && a.Notary.Disabled:
		return fmt.Errorf("auditpulumi: Keys.Seal is set and the installation has no notary (Notary.Disabled, or no configured preset "+
			"provisions one): nothing signs with it. Configure Presets[%q] to have the notary and its seal key, or leave Keys.Seal out",
			profile.Standard)
	case k.Seal == "" && !a.Notary.Disabled:
		return errors.New("auditpulumi: Keys.Seal is required with the notary: the library creates no key, so name the " +
			"estate's P-384 signing key by alias (alias/<name>), with a key policy that lets the notary's role sign (SealKeyPolicy)")
	}
	if k.Pseudonym != "" || k.Conceal != "" {
		profiles, err := pseudonymProfiles(a)
		if err != nil {
			return err
		}
		if !f.PseudonymKeys && len(profiles) == 0 {
			return fmt.Errorf("auditpulumi: Keys.Pseudonym and Keys.Conceal are for an installation that pseudonymises: no configured preset "+
				"provisions pseudonym keys, and no profile of Writer.DeploymentYAML replaces an identity with a pseudonym. "+
				"Configure Presets[%q], or compose a profile that pseudonymises", profile.Attested)
		}
		if a.Ingest.Disabled {
			return errors.New("auditpulumi: Keys.Pseudonym and Keys.Conceal are the writer's, and Ingest.Disabled leaves the writer out")
		}
		if a.Writer.Keys != nil {
			return errors.New("auditpulumi: Keys.Pseudonym/Keys.Conceal and Writer.Keys both configure the writer's keys: " +
				"Writer.Keys is the first releases' provider shape (transit over a public address); use one")
		}
	}
	if k.Conceal != "" && k.Pseudonym == "" {
		return errors.New("auditpulumi: Keys.Conceal seals the identity behind a pseudonym, and there is no Keys.Pseudonym")
	}
	return nil
}

var instanceRE = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$`)

// pseudonymProfiles names the profiles of Writer.DeploymentYAML that replace an
// identity with a pseudonym, which are the ones that need the pseudonym key. An
// installation without a document has none.
func pseudonymProfiles(a *Args) ([]string, error) {
	if !a.hasDocument {
		return nil, nil
	}
	frameworks, err := profile.Builtin()
	if err != nil {
		return nil, fmt.Errorf("auditpulumi: the framework profiles: %w", err)
	}
	names, err := a.deployment.PseudonymProfiles(frameworks)
	if err != nil {
		return nil, fmt.Errorf("auditpulumi: Writer.DeploymentYAML: %w", err)
	}
	return names, nil
}

// resolvedKeys are the ARNs the aliases point at.
type resolvedKeys struct {
	Archive, Seal, Pseudonym, Conceal string
}

// lookupAlias resolves one KMS alias to the ARN of the key behind it: the one
// lookup the keys of the installation (Keys) and the keys of the archive's
// destinations (their key_alias) both go through. An alias that does not exist is
// the estate's to create first, and the refusal says so, naming the field.
func lookupAlias(ctx *pulumi.Context, field, alias string, opts ...pulumi.InvokeOption) (string, error) {
	r, err := kms.LookupAlias(ctx, &kms.LookupAliasArgs{Name: alias}, opts...)
	if err != nil {
		return "", fmt.Errorf("auditpulumi: %s %s: the alias does not resolve (create the key and its alias in the estate first, "+
			"the library creates none): %w", field, alias, err)
	}
	if r.TargetKeyArn == "" {
		return "", fmt.Errorf("auditpulumi: %s %s: the alias points at no key", field, alias)
	}
	return r.TargetKeyArn, nil
}

// lookupKeys resolves each alias the arguments name to its key's ARN, as an
// invoke made through the component's own provider. An alias that does not
// exist is the estate's to create first, and the refusal says so.
func lookupKeys(ctx *pulumi.Context, a *Args, opts ...pulumi.InvokeOption) (resolvedKeys, error) {
	var out resolvedKeys
	for _, k := range []struct {
		field, alias string
		into         *string
	}{
		{"Keys.Archive", a.Keys.Archive, &out.Archive},
		{"Keys.Seal", a.Keys.Seal, &out.Seal},
		{"Keys.Pseudonym", a.Keys.Pseudonym, &out.Pseudonym},
		{"Keys.Conceal", a.Keys.Conceal, &out.Conceal},
	} {
		if k.alias == "" {
			continue
		}
		arn, err := lookupAlias(ctx, k.field, k.alias, opts...)
		if err != nil {
			return resolvedKeys{}, err
		}
		*k.into = arn
	}
	return out, nil
}

// instance is the name the encryption context carries.
func (a *Args) instance(name string) string {
	if a.Keys.Instance != "" {
		return a.Keys.Instance
	}
	return name
}

// The purposes of the storage port the installation's grants condition on.
const (
	purposePseudonym = "pseudonym"
	purposeConceal   = "conceal"
)

// writerKeyStatements are the writer's grants on the keys of the installation
// (the archive key is granted separately, as it always was). The conditions
// are the encryption context the storage KMS backend sends: the pseudonym
// secrets are wrapped with {purpose, tenant}, so the grant fixes the purpose;
// the conceal key is used with the default context {instance, purpose}, so the
// grant fixes both, and a principal that does not send them cannot use the key.
func writerKeyStatements(k resolvedKeys, instance string) []statement {
	var st []statement
	if k.Pseudonym != "" {
		st = append(st, allow([]string{"kms:GenerateDataKey", "kms:Decrypt"}, []string{k.Pseudonym}, map[string]any{
			"StringEquals": map[string]any{"kms:EncryptionContext:purpose": purposePseudonym},
		}))
	}
	if k.Conceal != "" {
		st = append(st, allow([]string{"kms:Encrypt", "kms:Decrypt", "kms:GenerateDataKey"}, []string{k.Conceal}, map[string]any{
			"StringEquals": map[string]any{
				"kms:EncryptionContext:instance": instance,
				"kms:EncryptionContext:purpose":  purposeConceal,
			},
		}))
	}
	return st
}

// ---- the installation's state store

// defaultCredentialsAddress is where the credentials of the preset's store at an
// endpoint are, below the state root, unless Presets[...].CredentialsAddress says
// otherwise: <default>/<preset>.
const (
	defaultCredentialsAddress = "internal/archive"
	pseudonymStateAddress     = "internal/pseudonym"
)

var addressRE = regexp.MustCompile(`^internal(/[A-Za-z0-9_][A-Za-z0-9_.-]*)+$`)

// checkStateRoot holds a state root to what Writer.Secrets.Root is held to.
func checkStateRoot(root, name string) error {
	if !rootRE.MatchString(root) || !strings.HasPrefix(root, "/audit/") {
		return fmt.Errorf("auditpulumi: State.Root %q must be an SSM parameter path under /audit/ such as /audit/%s: "+
			"at least two segments, the first `audit`, segments of letters, digits, . _ and -, no trailing slash, no wildcard", root, name)
	}
	for _, seg := range strings.Split(root[1:], "/") {
		if seg == "." || seg == ".." || strings.HasPrefix(seg, ".") {
			return fmt.Errorf("auditpulumi: State.Root %q has the segment %q: no segment may start with a dot", root, seg)
		}
	}
	return nil
}

// stateGrant is what a role is given of the installation's state store: read
// some parameters, read and create others.
type stateGrant struct {
	Region, Account, KeyArn string
	// Read are parameter paths read; Write are path prefixes (with /*) read and
	// created.
	Read, Write []string
}

func (g *stateGrant) arn(path string) string {
	return "arn:" + "aws:ssm:" + g.Region + ":" + g.Account + ":parameter" + path
}

func (g *stateGrant) statements() []statement {
	if g == nil || (len(g.Read) == 0 && len(g.Write) == 0) {
		return nil
	}
	var st []statement
	if len(g.Read) > 0 {
		arns := make([]string, len(g.Read))
		for i, p := range g.Read {
			arns[i] = g.arn(p)
		}
		st = append(st, allow([]string{"ssm:GetParameter"}, arns, nil))
	}
	if len(g.Write) > 0 {
		arns := make([]string, len(g.Write))
		for i, p := range g.Write {
			arns[i] = g.arn(p)
		}
		// PutParameter without overwrite creates a parameter and fails on an
		// existing one, which is what the state store's PutIfAbsent relies on; the
		// role is not granted a way to replace or delete one.
		st = append(st, allow([]string{"ssm:GetParameter", "ssm:PutParameter"}, arns, nil))
	}
	if g.KeyArn != "" {
		actions := []string{"kms:Decrypt"}
		if len(g.Write) > 0 {
			actions = append(actions, "kms:GenerateDataKey", "kms:Encrypt")
		}
		st = append(st, allow(actions, []string{g.KeyArn}, map[string]any{
			"StringEquals": map[string]any{"kms:ViaService": "ssm." + g.Region + ".amazonaws.com"},
		}))
	}
	return st
}

// checkEndpoint holds an endpoint to an https URL with a host and no path.
func checkEndpoint(field, endpoint string) error {
	u, err := url.Parse(endpoint)
	if err != nil || u.Scheme != "https" || u.Host == "" || u.User != nil || (u.Path != "" && u.Path != "/") || u.RawQuery != "" {
		return fmt.Errorf("auditpulumi: %s %q must be an https URL with a host and no path or credentials: "+
			"the credentials are kept in the state store, and a request to the store crosses this URL", field, endpoint)
	}
	return nil
}
