// Command goreleaser-snapshot-config derives a single-architecture copy of
// .goreleaser.yaml for the local and CI loops that build straight into the
// kind box's own registry (see hack/example-snapshot.sh).
//
// Everything in the release configuration stays exactly as written — same
// hooks, same images, same tags — except one thing: every image's
// `platforms` list, and the plain Go `builds` a `kos` entry compiles from,
// are narrowed to the ONE architecture the caller asks for. The kind box's
// node is one architecture, so a second one would only be built and
// discarded.
//
// The derived file is produced by this command, not hand-maintained: the
// alternative is a second release configuration that can drift from the
// first one silently.
//
// Ported from truvity/policy's hack/goreleaser-snapshot-config, which has no
// policy-specific logic in it — this repository uses sigs.k8s.io/yaml (an
// existing dependency here) in place of go.yaml.in/yaml/v3, which is not.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"sigs.k8s.io/yaml"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "goreleaser-snapshot-config:", err)
		os.Exit(1)
	}
}

func run() error {
	in := flag.String("in", ".goreleaser.yaml", "the release configuration to derive from")
	out := flag.String("out", "", "where to write the derived configuration (required)")
	platform := flag.String("platform", "", "the one platform to keep, e.g. linux/amd64 (required)")
	flag.Parse()

	if *out == "" || *platform == "" {
		return fmt.Errorf("both -out and -platform are required")
	}

	raw, err := os.ReadFile(*in)
	if err != nil {
		return fmt.Errorf("read %s: %w", *in, err)
	}

	var config map[string]any
	if err := yaml.Unmarshal(raw, &config); err != nil {
		return fmt.Errorf("parse %s: %w", *in, err)
	}

	arch, ok := strings.CutPrefix(*platform, "linux/")
	if !ok {
		return fmt.Errorf("-platform %q: only linux/<arch> is supported, matching this repository's own images", *platform)
	}

	narrowed := 0
	for _, section := range []string{"kos", "dockers_v2"} {
		images, ok := config[section].([]any)
		if !ok {
			continue
		}

		for _, entry := range images {
			image, ok := entry.(map[string]any)
			if !ok {
				continue
			}

			if _, ok := image["platforms"]; !ok {
				continue
			}

			image["platforms"] = []any{*platform}
			narrowed++
		}
	}

	if narrowed == 0 {
		return fmt.Errorf("%s: no kos or dockers_v2 image declared a platforms list — this would silently do nothing", *in)
	}

	// The plain Go binaries a `kos` entry cross-compiles from. Narrowing
	// only `kos[].platforms` above still leaves GoReleaser compiling (and
	// archiving) the OTHER architecture's binary here.
	if builds, ok := config["builds"].([]any); ok {
		for _, entry := range builds {
			build, ok := entry.(map[string]any)
			if !ok {
				continue
			}

			if _, ok := build["goarch"]; !ok {
				continue
			}

			build["goarch"] = []any{arch}
		}
	}

	rendered, err := yaml.Marshal(config)
	if err != nil {
		return fmt.Errorf("render derived configuration: %w", err)
	}

	header := fmt.Sprintf(
		"# GENERATED by hack/goreleaser-snapshot-config from %s — do not edit.\n"+
			"# Every image here is narrowed to %s. See that command's own\n"+
			"# doc comment for why, and %s for the real release.\n",
		*in, *platform, *in,
	)

	if err := os.WriteFile(*out, append([]byte(header), rendered...), 0o644); err != nil { //nolint:gosec,mnd
		return fmt.Errorf("write %s: %w", *out, err)
	}

	return nil
}
