// Package sluis carries the files this repository publishes as data.
package sluis

import "embed"

// ConfigSchemas are the schemas of each binary's configuration file, under
// schemas/config/. They are generated by `just config-schemas` from
// internal/config and committed, so that a deployment can validate its file
// without this repository's code, and so that the binary validates against
// the very file a chart's tests do.
//
//go:embed schemas/config/*.schema.json
var ConfigSchemas embed.FS
