// Package sluis carries the files this repository publishes as data.
package sluis

import "embed"

// ConfigSchemas are the schemas of the configuration documents, under
// schemas/config/: the three service documents and the policy document. They
// are generated by `just config-schemas` from internal/config and committed,
// so that a deployment can validate its file without this repository's code,
// and so that the binary validates against the very file a chart's tests do.
// schemas/config/v1/ holds the v1 service documents' schemas, frozen: a v1
// document is held to its own schema before it is converted.
//
//go:embed schemas/config/*.schema.json schemas/config/v1/*.schema.json
var ConfigSchemas embed.FS
