package issuerapp_test

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/truvity/sluis/internal/config"
	"github.com/truvity/sluis/internal/issuerapp"
	"github.com/truvity/sluis/internal/kmsfake"
	"github.com/truvity/sluis/internal/port"
	"github.com/truvity/sluis/internal/store"
)

func wrappedSecret(t *testing.T) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "state")
	if err := os.WriteFile(p, []byte(base64.StdEncoding.EncodeToString(randomBytes(32))+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

func wrappedConfig(t *testing.T, k *config.SigningKeyKMSWrapped) func(*config.Serve) {
	t.Helper()
	k.StateSecret = asName(wrappedSecret(t))
	return func(f *config.Serve) { f.SigningKey = &config.SigningKey{KMSWrapped: k} }
}

type jwksKey struct{ Kid, Alg, Kty, Crv string }

func keysOf(t *testing.T, app *issuerapp.App) []jwksKey {
	t.Helper()
	code, body := get(t, app.Handler(), "/keys")
	if code != 200 {
		t.Fatalf("/keys = %d", code)
	}
	var jwks struct{ Keys []jwksKey }
	if err := json.Unmarshal([]byte(body), &jwks); err != nil {
		t.Fatal(err)
	}
	return jwks.Keys
}

// The JWKS of a KMS-wrapped installation carries one public key per configured
// algorithm, generated by KMS, and the private halves are wrapped.
func TestKMSWrappedKeysArePublishedPerAlgorithm(t *testing.T) {
	t.Parallel()
	fake := kmsfake.New()
	app := bootDeps(t, issuerapp.Deps{Directory: nobody{}, KMSWrapped: fake},
		wrappedConfig(t, &config.SigningKeyKMSWrapped{KeyID: "alias/sluis-wrapped"}))
	byAlg := map[string]jwksKey{}
	for _, k := range keysOf(t, app) {
		byAlg[k.Alg] = k
	}
	if len(byAlg) != 2 || byAlg["ES384"].Crv != "P-384" || byAlg["RS256"].Kty != "RSA" {
		t.Fatalf("keys = %+v", byAlg)
	}
	if fake.Generated != 2 {
		t.Errorf("generated %d key pairs", fake.Generated)
	}
	for _, c := range fake.Contexts {
		if c["purpose"] != "sluis-signing" || c["kid"] == "" || c["alg"] == "" {
			t.Errorf("context %v", c)
		}
	}
}

func TestKMSWrappedCanSignOnlyES384(t *testing.T) {
	t.Parallel()
	fake := kmsfake.New()
	app := bootDeps(t, issuerapp.Deps{Directory: nobody{}, KMSWrapped: fake},
		wrappedConfig(t, &config.SigningKeyKMSWrapped{KeyID: "k", Algorithms: []string{"ES384"}}))
	if keys := keysOf(t, app); len(keys) != 1 || keys[0].Alg != "ES384" || fake.Generated != 1 {
		t.Fatalf("keys = %+v, generated %d", keys, fake.Generated)
	}
}

func TestKMSWrappedConfigIsValidated(t *testing.T) {
	t.Parallel()
	d := func(s string) *config.Duration {
		v, _ := time.ParseDuration(s)
		c := config.Duration(v)
		return &c
	}
	for name, tc := range map[string]struct {
		key  *config.SigningKey
		want string
	}{
		"with a file": {&config.SigningKey{File: "/k", KMSWrapped: &config.SigningKeyKMSWrapped{KeyID: "k", StateSecret: "s"}}, "exclusive"},
		"with kms": {&config.SigningKey{KMS: &config.SigningKeyKMS{Keys: []string{"k"}, StateSecret: "s"},
			KMSWrapped: &config.SigningKeyKMSWrapped{KeyID: "k", StateSecret: "s"}}, "exclusive"},
		"no key":    {&config.SigningKey{KMSWrapped: &config.SigningKeyKMSWrapped{StateSecret: "s"}}, "keyId"},
		"no secret": {&config.SigningKey{KMSWrapped: &config.SigningKeyKMSWrapped{KeyID: "k"}}, "stateSecret"},
		"eddsa": {&config.SigningKey{KMSWrapped: &config.SigningKeyKMSWrapped{
			KeyID: "k", StateSecret: "s", Algorithms: []string{"EdDSA"}}}, "EdDSA is not supported"},
		"short retain": {&config.SigningKey{KMSWrapped: &config.SigningKeyKMSWrapped{KeyID: "k", StateSecret: "s", Retain: d("30m")}}, "retain"},
		"rotate soon": {&config.SigningKey{KMSWrapped: &config.SigningKeyKMSWrapped{
			KeyID: "k", StateSecret: "s", RotateEvery: d("10m")}}, "longer than prepublish"},
	} {
		_, err := issuerapp.FromConfig(withPolicy(t, &config.Serve{IssuerURL: "https://issuer.example", SigningKey: tc.key}))
		if err == nil || !strings.Contains(err.Error(), tc.want) {
			t.Errorf("%s: %v, want %q", name, err, tc.want)
		}
	}
}

// A preset that names kms-wrapped, with the settings in `adapters.signing` or
// resolved from `signingKey.kmsWrapped`, builds the same installation.
func TestKMSWrappedFromTheSigningAdapter(t *testing.T) {
	t.Parallel()
	secret := wrappedSecret(t)
	fake := kmsfake.New()
	plan := port.Table{port.ConcernSigning: {Adapter: "kms-wrapped", Settings: port.Settings{
		"keyId": "alias/sluis-wrapped", "stateSecret": asName(secret), "algorithms": []any{"RS256"}}}}
	app := bootDeps(t, issuerapp.Deps{Directory: nobody{}, KMSWrapped: fake, Stores: &store.Stores{Plan: plan, Secrets: testSecrets}})
	if keys := keysOf(t, app); len(keys) != 1 || keys[0].Alg != "RS256" {
		t.Fatalf("keys = %+v", keys)
	}

}
