package issuerapp_test

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/truvity/sluis/internal/config"
	"github.com/truvity/sluis/internal/issuerapp"
	"github.com/truvity/sluis/internal/port"
	"github.com/truvity/sluis/internal/store"
	"github.com/truvity/sluis/storage/keys"
	"github.com/truvity/sluis/storage/keys/local"
)

// fakeKMS is a key service that answers to the name "kms", over the local
// backend (which refuses a wrong context, as KMS does), and records what the
// wrapped ring encrypts.
type fakeKMS struct {
	*local.Backend
	mu         sync.Mutex
	Generated  int
	Contexts   []map[string]string
	Plaintexts [][]byte
}

func newFakeKMS(t *testing.T) *fakeKMS {
	t.Helper()
	b, err := local.New(local.RandomRoot())
	if err != nil {
		t.Fatal(err)
	}
	return &fakeKMS{Backend: b}
}

func (*fakeKMS) Name() string                   { return "kms" }
func (*fakeKMS) ValidateName(name string) error { return nil }

func (f *fakeKMS) Encrypt(ctx context.Context, key string, pt []byte, ec map[string]string) ([]byte, error) {
	f.mu.Lock()
	f.Generated++
	f.Contexts = append(f.Contexts, ec)
	f.Plaintexts = append(f.Plaintexts, append([]byte(nil), pt...))
	f.mu.Unlock()
	return f.Backend.Encrypt(ctx, key, pt, ec)
}

// signKeysBlock is `keys: {adapter: kms, sign: alias/<name>}`.
func signKeysBlock(alias string) *keys.Config {
	return &keys.Config{Adapter: "kms", Keys: map[keys.Purpose]keys.Entry{keys.Sign: {Key: alias}}}
}

func wrappedSecret(t *testing.T) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "state")
	if err := os.WriteFile(p, []byte(base64.StdEncoding.EncodeToString(randomBytes(32))+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

func wrappedConfig(t *testing.T, k *config.SigningKeyKMSWrapped) func(*config.Serve) {
	t.Helper()
	k.StateSecret = asName(wrappedSecret(t))
	return func(f *config.Serve) {
		f.SigningKey = &config.SigningKey{KMSWrapped: k}
		if k.KeyID == "" {
			f.Instance = "acme"
			f.Keys = signKeysBlock("alias/sluis-acme-sign")
		}
	}
}

type jwksKey struct{ Kid, Alg, Kty, Crv string }

func keysOf(t *testing.T, app *issuerapp.App) []jwksKey {
	t.Helper()
	code, body := get(t, app.Handler(), "/keys")
	if code != 200 {
		t.Fatalf("/keys = %d", code)
	}
	var jwks struct{ Keys []jwksKey }
	if err := json.Unmarshal([]byte(body), &jwks); err != nil {
		t.Fatal(err)
	}
	return jwks.Keys
}

// The JWKS of a KMS-wrapped installation carries one public key per configured
// algorithm, generated by KMS, and the private halves are wrapped.
func TestKMSWrappedKeysArePublishedPerAlgorithm(t *testing.T) {
	fake := newFakeKMS(t)
	app := bootDeps(t, issuerapp.Deps{Directory: nobody{}, Keys: fake},
		wrappedConfig(t, &config.SigningKeyKMSWrapped{}))
	byAlg := map[string]jwksKey{}
	for _, k := range keysOf(t, app) {
		byAlg[k.Alg] = k
	}
	if len(byAlg) != 2 || byAlg["ES384"].Crv != "P-384" || byAlg["RS256"].Kty != "RSA" {
		t.Fatalf("keys = %+v", byAlg)
	}
	if fake.Generated != 2 {
		t.Errorf("generated %d key pairs", fake.Generated)
	}
	for _, c := range fake.Contexts {
		if len(c) != 2 || c["purpose"] != "sign" || c["instance"] != "acme" {
			t.Errorf("context %v", c)
		}
	}
}

func TestKMSWrappedCanSignOnlyES384(t *testing.T) {
	fake := newFakeKMS(t)
	app := bootDeps(t, issuerapp.Deps{Directory: nobody{}, Keys: fake},
		wrappedConfig(t, &config.SigningKeyKMSWrapped{Algorithms: []string{"ES384"}}))
	if ks := keysOf(t, app); len(ks) != 1 || ks[0].Alg != "ES384" || fake.Generated != 1 {
		t.Fatalf("keys = %+v, generated %d", ks, fake.Generated)
	}
}

func TestKMSWrappedConfigIsValidated(t *testing.T) {
	d := func(s string) *config.Duration {
		v, _ := time.ParseDuration(s)
		c := config.Duration(v)
		return &c
	}
	for name, tc := range map[string]struct {
		key  *config.SigningKey
		want string
	}{
		"with a file": {&config.SigningKey{File: "/k", KMSWrapped: &config.SigningKeyKMSWrapped{KeyID: "alias/k", StateSecret: "s"}}, "exclusive"},
		"with kms": {&config.SigningKey{KMS: &config.SigningKeyKMS{Keys: []string{"k"}, StateSecret: "s"},
			KMSWrapped: &config.SigningKeyKMSWrapped{KeyID: "alias/k", StateSecret: "s"}}, "exclusive"},
		"no key":    {&config.SigningKey{KMSWrapped: &config.SigningKeyKMSWrapped{StateSecret: "s"}}, "keys.sign"},
		"no secret": {&config.SigningKey{KMSWrapped: &config.SigningKeyKMSWrapped{KeyID: "alias/k"}}, "stateSecret"},
		"an ARN":    {&config.SigningKey{KMSWrapped: &config.SigningKeyKMSWrapped{KeyID: "arn:aws:kms:eu-west-1:111122223333:key/abc", StateSecret: "s"}}, "not an alias"},
		"eddsa": {&config.SigningKey{KMSWrapped: &config.SigningKeyKMSWrapped{
			KeyID: "alias/k", StateSecret: "s", Algorithms: []string{"EdDSA"}}}, "EdDSA is not supported"},
		"short retain": {&config.SigningKey{KMSWrapped: &config.SigningKeyKMSWrapped{KeyID: "alias/k", StateSecret: "s", Retain: d("30m")}}, "retain"},
		"rotate soon": {&config.SigningKey{KMSWrapped: &config.SigningKeyKMSWrapped{
			KeyID: "alias/k", StateSecret: "s", RotateEvery: d("10m")}}, "longer than prepublish"},
	} {
		_, err := issuerapp.FromConfig(withPolicy(t, &config.Serve{IssuerURL: "https://issuer.example", SigningKey: tc.key}))
		if err == nil || !strings.Contains(err.Error(), tc.want) {
			t.Errorf("%s: %v, want %q", name, err, tc.want)
		}
	}
}

// A preset that names kms-wrapped, with the settings in `adapters.signing` or
// resolved from `signingKey.kmsWrapped`, builds the same installation.
func TestKMSWrappedFromTheSigningAdapter(t *testing.T) {
	secret := wrappedSecret(t)
	fake := newFakeKMS(t)
	plan := port.Table{port.ConcernSigning: {Adapter: "kms-wrapped", Settings: port.Settings{
		"keyId": "alias/sluis-wrapped", "stateSecret": asName(secret), "algorithms": []any{"RS256"}}}}
	app := bootDeps(t, issuerapp.Deps{Directory: nobody{}, Keys: fake, Stores: &store.Stores{Plan: plan, Secrets: testSecrets}})
	if ks := keysOf(t, app); len(ks) != 1 || ks[0].Alg != "RS256" {
		t.Fatalf("keys = %+v", ks)
	}
	// The deprecated keyId is mapped onto keys.sign, under the default context.
	if len(fake.Contexts) == 0 || fake.Contexts[0]["purpose"] != "sign" {
		t.Errorf("contexts %v", fake.Contexts)
	}

}

// The deprecated keyId, an alias, is the sign key when `keys` says none.
func TestKMSWrappedKeyIDIsMappedOntoKeysSign(t *testing.T) {
	fake := newFakeKMS(t)
	app := bootDeps(t, issuerapp.Deps{Directory: nobody{}, Keys: fake},
		wrappedConfig(t, &config.SigningKeyKMSWrapped{KeyID: "alias/sluis-wrapped", Algorithms: []string{"ES384"}}))
	if ks := keysOf(t, app); len(ks) != 1 || fake.Generated != 1 {
		t.Fatalf("keys = %+v, generated %d", ks, fake.Generated)
	}
	if c := fake.Contexts[0]; c["purpose"] != "sign" || c["instance"] == "" {
		t.Errorf("context %v", c)
	}
}

// Moving from direct asymmetric KMS signing to the wrapped ring: the old public
// key (exported from KMS) is published verify-only for the overlap, the new
// ring signs, and tokens the old key signed still find their key by kid.
func TestSwitchFromDirectKMSSigningToTheWrappedRing(t *testing.T) {
	old, err := ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	der, _ := x509.MarshalPKIXPublicKey(&old.PublicKey)
	pubFile := filepath.Join(t.TempDir(), "old.pem")
	if err := os.WriteFile(pubFile, pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der}), 0o600); err != nil {
		t.Fatal(err)
	}
	const oldKid = "kms-direct-1"
	until := time.Now().Add(48 * time.Hour).UTC().Format(time.RFC3339)

	fake := newFakeKMS(t)
	app := bootDeps(t, issuerapp.Deps{Directory: nobody{}, Keys: fake}, func(f *config.Serve) {
		wrappedConfig(t, &config.SigningKeyKMSWrapped{Algorithms: []string{"ES384"}})(f)
		f.SigningKey.VerifyOnly = []config.SigningKeyVerifyOnly{{File: pubFile, KeyID: oldKid, Alg: "ES384", Until: until}}
	})
	ks := keysOf(t, app)
	if len(ks) != 2 {
		t.Fatalf("keys = %+v, want the old (verify-only) and the new ring's", ks)
	}
	var sawOld, sawNew bool
	for _, k := range ks {
		if k.Kid == oldKid {
			sawOld = true
		} else {
			sawNew = true
		}
	}
	if !sawOld || !sawNew || fake.Generated != 1 {
		t.Errorf("old published %v, new published %v, generated %d", sawOld, sawNew, fake.Generated)
	}
}
