// Package matrixdoc renders the adapter compatibility and implementation
// matrix, docs/reference/adapters.md, from the adapter registry and the
// preset table. The file is generated: run `just adapters-doc` after adding,
// removing or changing an adapter's descriptor. A test fails when the
// committed file is not what Render returns.
package matrixdoc

import (
	"fmt"
	"strings"

	"github.com/truvity/sluis/internal/port"

	// The store package imports every adapter the long-running process can
	// run, so each has registered itself by the time Render reads the
	// registry.
	_ "github.com/truvity/sluis/internal/store"

	// Adapters that only another binary imports. The matrix must see every
	// adapter ANY binary registers, or it marks a built one as planned (the
	// invoke trigger is imported by cmd/sluis-lambda alone, and the matrix
	// said "on request" for it). TestEveryRegisteringPackageIsInTheMatrix
	// fails when a package that registers an adapter is missing from here.
	_ "github.com/truvity/sluis/internal/port/invoke"
)

// File is where the generated matrix lives, relative to the repository root.
const File = "docs/reference/adapters.md"

const (
	yes       = "✅"
	no        = "—"
	done      = "✅ implemented"
	requested = "💤 on request"
)

// Render returns the contents of [File].
func Render() string {
	return render(port.Default.Matrix())
}

func render(all []port.Descriptor) string {
	var b strings.Builder
	b.WriteString(`<!-- Code generated by internal/port/matrixdoc; DO NOT EDIT. Run ` + "`just adapters-doc`" + `. -->

# Adapters: compatibility and implementation matrix

Every adapter, per concern, from the registry in ` + "`internal/port`" + `. To pick one,
start with [choosing a deployment](../guides/choosing-a-deployment.md); to add one,
see [adding an adapter in a fork](../guides/diy-adapter.md); for how adapters,
presets and the platform fit together, see
[design/ports.md](../design/ports.md#adapters-presets-and-the-platform).

- ` + done + `: built and registered; the maintainers' estates run it.
- ` + requested + `: designed and in the catalogue, not built; start refuses it. It is built when a user asks.
- **Needs**: a platform answer that must be yes (` + "`AWS`, `Kubernetes`, `OpenBao`" + `).
- **Runtimes**: where the sluis process itself may run (` + "`kubernetes`, `lambda`, `process`" + `).
- Hosting is a deployment choice, not code: one adapter covers several providers
  (the ` + "`valkey`" + ` adapter is ElastiCache, MemoryDB, in-cluster or external).

`)
	for _, c := range port.Concerns {
		fmt.Fprintf(&b, "## %s\n\n", c)
		b.WriteString("| Adapter | Status | AWS | Kubernetes | OpenBao | kubernetes | lambda | process | What it is |\n")
		b.WriteString("|---|---|---|---|---|---|---|---|---|\n")
		for _, d := range all {
			if d.Concern != c {
				continue
			}
			st := done
			if d.Status != port.StatusImplemented {
				st = requested
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s | %s | %s |\n", d.Name, st,
				mark(d.Requires.AWS, "needs"), mark(d.Requires.Kubernetes, "needs"), mark(d.Requires.OpenBao, "needs"),
				mark(d.Works(port.RuntimeKubernetes), yes), mark(d.Works(port.RuntimeLambda), yes), mark(d.Works(port.RuntimeProcess), yes),
				strings.ReplaceAll(d.Summary, "|", `\|`))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Presets\n\nThe adapter each preset names per concern. " + requested +
		" marks an adapter that is not built, so that preset is not usable until it is.\n\n")
	b.WriteString("| Concern |")
	sep := "|---|"
	for _, p := range port.Presets {
		fmt.Fprintf(&b, " `%s` |", p)
		sep += "---|"
	}
	b.WriteString("\n" + sep + "\n")
	status := map[[2]string]port.Status{}
	for _, d := range all {
		status[[2]string{string(d.Concern), d.Name}] = d.Status
	}
	for _, c := range port.Concerns {
		fmt.Fprintf(&b, "| %s |", c)
		for _, p := range port.Presets {
			name := port.PresetTable(p)[c]
			cell := "`" + name + "`"
			if s, ok := status[[2]string{string(c), name}]; !ok || s != port.StatusImplemented {
				cell += " 💤"
			}
			fmt.Fprintf(&b, " %s |", cell)
		}
		b.WriteString("\n")
	}
	b.WriteString("\n### Availability\n\nA preset that names an adapter which is not built is **unavailable**: " +
		"start refuses it with a message naming the preset, unless `adapters` replaces every planned adapter it names. " +
		"Unavailable now:\n\n")
	for _, p := range port.Presets {
		if why := p.Unavailable(); why != "" {
			fmt.Fprintf(&b, "- `%s`: %s.\n", p, why)
		}
	}
	fmt.Fprintf(&b, "\nAvailable: %s.\n", presetList(port.BuiltPresets()))
	b.WriteString("\n`aws-eks` is the deprecated name of `k8s-aws`: it resolves to it, and start warns.\n\n")
	return b.String()
}

func presetList(ps []port.Preset) string {
	var out []string
	for _, p := range ps {
		out = append(out, "`"+string(p)+"`")
	}
	return strings.Join(out, ", ")
}

func mark(on bool, yesText string) string {
	if on {
		return yesText
	}
	return no
}
