-- The wrapped per-tenant secrets behind pseudonyms, for a deployment whose key
-- service is a KMS (keys.adapter kms) and which keeps no SSM Parameter Store.
--
-- Each row is a data key generated by KMS for one (purpose, tenant) and wrapped
-- under the purpose's KMS key with the encryption context {purpose, tenant}: the
-- column is ciphertext, useless without the KMS key. A destroyed tenant is a row
-- in the tombstone table and no row here, so a tenant erased is told apart from
-- one never seen, and a first use racing the erasure cannot bring the key back.
--
-- The writer's role owns neither table (the migration's role does); it is granted
-- what it needs, and the query service and the indexer none of it.
create table if not exists audit_wrapped_keys (
    id         text        primary key,
    wrapped    bytea       not null check (length(wrapped) > 0),
    created_at timestamptz not null default now()
);

create table if not exists audit_wrapped_key_tombstones (
    id           text        primary key,
    destroyed_at timestamptz not null default now()
);

insert into audit_schema_version (version) values (7) on conflict do nothing;
