// Code generated by `just audit-sentences` from internal/audit/catalogue/roster.yaml. DO NOT EDIT.
import type { Sentences } from "@truvity/audit";

export const roster: Sentences = {
  "source": "roster",
  "version": "1.7.0",
  "locales": [
    "en"
  ],
  "actions": {
    "roster.catalogue_app.created": {
      "summary": "A catalogued GitHub App was created.",
      "message": {
        "en": "{actor} created GitHub App {targets_0_id} for {targets_1_id}"
      }
    },
    "roster.catalogue_app.disconnected": {
      "summary": "A catalogued GitHub App was disconnected.",
      "message": {
        "en": "{actor} disconnected GitHub App {targets_0_id} from {targets_1_id}"
      }
    },
    "roster.catalogue_app.installed": {
      "summary": "A catalogued GitHub App was installed.",
      "message": {
        "en": "{actor} installed GitHub App {targets_0_id} on {targets_1_id}"
      }
    },
    "roster.github_app.created": {
      "summary": "A GitHub App was created for an organisation.",
      "message": {
        "en": "{actor} created GitHub App {targets_0_id} for {targets_1_id}"
      }
    },
    "roster.github_link.created": {
      "summary": "A person linked their GitHub account.",
      "message": {
        "en": "{actor} linked a GitHub account"
      }
    },
    "roster.github_link.imported": {
      "summary": "An operator imported a link between a GitHub account and a person.",
      "message": {
        "en": "{actor} linked a GitHub account to {subject}"
      }
    },
    "roster.github_link.lost": {
      "summary": "A link was lost.",
      "message": {
        "en": "{subject}'s GitHub link was lost"
      }
    },
    "roster.github_link.matched": {
      "summary": "A GitHub account was linked to a person because its profile publishes their work address.",
      "message": {
        "en": "a GitHub account was linked to {subject} by the address its profile publishes"
      }
    },
    "roster.github_link.moved": {
      "summary": "A link moved to another address of the same person.",
      "message": {
        "en": "{subject}'s GitHub link moved"
      }
    },
    "roster.github_link.narrowed": {
      "summary": "A link lost some of its addresses.",
      "message": {
        "en": "{subject}'s GitHub link was narrowed"
      }
    },
    "roster.github_link.unverifiable": {
      "summary": "A link could no longer be verified.",
      "message": {
        "en": "{subject}'s GitHub link can no longer be verified"
      }
    },
    "roster.github_member.added": {
      "summary": "A person was added to a GitHub team.",
      "message": {
        "en": "{outcome, select, success {{subject} was added to {targets_0_id}} other {GitHub refused to add {subject} to {targets_0_id}}}"
      }
    },
    "roster.github_member.held": {
      "summary": "A change to a person's GitHub membership is held, and needs an operator.",
      "message": {
        "en": "a change to {subject} on {targets_0_id} is held: {outcome_reason}"
      }
    },
    "roster.github_member.invited": {
      "summary": "A person was invited to a GitHub organisation or team.",
      "message": {
        "en": "{outcome, select, success {{subject} was invited to {targets_0_id}} other {GitHub refused to invite {subject} to {targets_0_id}}}"
      }
    },
    "roster.github_member.removed": {
      "summary": "A person was removed from a GitHub organisation or team.",
      "message": {
        "en": "{outcome, select, success {{subject} was removed from {targets_0_id}} other {GitHub refused to remove {subject} from {targets_0_id}}}"
      }
    },
    "roster.github_member.role_set": {
      "summary": "A person's role on a GitHub team changed.",
      "message": {
        "en": "{outcome, select, success {{subject} became {data_role} of {targets_0_id}} other {GitHub refused to make {subject} {data_role} of {targets_0_id}}}"
      }
    },
    "roster.github_org.connected": {
      "summary": "A GitHub organisation was connected by installing the App.",
      "message": {
        "en": "{actor} connected GitHub organisation {targets_0_id}"
      }
    },
    "roster.github_org.disconnected": {
      "summary": "A GitHub organisation was disconnected.",
      "message": {
        "en": "{actor} disconnected GitHub organisation {targets_0_id}"
      }
    },
    "roster.github_org.owner_changed": {
      "summary": "The directory that owns a GitHub organisation was changed by the installation-wide operator.",
      "message": {
        "en": "{actor} changed the owner of GitHub organisation {targets_0_id} from {data_from} to {data_to}"
      }
    },
    "roster.github_org.pass_requested": {
      "summary": "An operator asked the GitHub controller to pass over an organisation now.",
      "message": {
        "en": "{actor} asked for a pass over GitHub organisation {targets_0_id} now"
      }
    },
    "roster.github_owner.reported": {
      "summary": "An organisation owner the directory does not vouch for was reported rather than removed.",
      "message": {
        "en": "an owner of {targets_0_id} was reported: {outcome_reason}"
      }
    },
    "roster.github_removals.confirmed": {
      "summary": "An operator confirmed a set of removals the safety breaker had held.",
      "message": {
        "en": "{actor} confirmed the removal of {data_affected} of {data_members} members of {targets_0_id}"
      }
    },
    "roster.github_token.minted": {
      "summary": "A GitHub App installation token was minted, or refused. Never the token.",
      "message": {
        "en": "{outcome, select, success {{actor} was given a {targets_0_id} token for {data_org}} denied {{actor} was refused a {targets_0_id} token} other {{actor} could not be given a {targets_0_id} token}}"
      }
    },
    "roster.link_app.connected": {
      "summary": "The App that links people's GitHub accounts was connected.",
      "message": {
        "en": "{actor} connected the account-linking App {targets_0_id}"
      }
    },
    "roster.link_app.disconnected": {
      "summary": "The App that links people's GitHub accounts was disconnected.",
      "message": {
        "en": "{actor} disconnected the account-linking App {targets_0_id}"
      }
    },
    "roster.person.signed_in": {
      "summary": "A person signed in to a client, or was refused.",
      "message": {
        "en": "{outcome, select, success {{actor} signed in to {targets_0_id}} denied {{actor} was refused sign-in to {targets_0_id}} other {{actor} could not sign in to {targets_0_id}}}"
      }
    },
    "roster.recovery.signed_in": {
      "summary": "Somebody signed in with the recovery identity, which bypasses the directory.",
      "message": {
        "en": "{outcome, select, success {{actor} signed in to {targets_0_id} by recovery} other {a recovery sign-in to {targets_0_id} did not complete}}"
      }
    },
    "roster.runner_app.created": {
      "summary": "A GitHub App for self-hosted runners was created.",
      "message": {
        "en": "{actor} created runner App {targets_0_id} for {targets_1_id}"
      }
    },
    "roster.runner_app.disconnected": {
      "summary": "A GitHub App for self-hosted runners was disconnected.",
      "message": {
        "en": "{actor} disconnected runner App {targets_0_id} from {targets_1_id}"
      }
    },
    "roster.runner_app.installed": {
      "summary": "A GitHub App for self-hosted runners was installed.",
      "message": {
        "en": "{actor} installed runner App {targets_0_id} on {targets_1_id}"
      }
    },
    "roster.session.ended": {
      "summary": "A person signed out, ending their sessions.",
      "message": {
        "en": "{actor} signed out, ending {data_ended, plural, one {# session} other {# sessions}}"
      }
    },
    "roster.session.refresh_refused": {
      "summary": "A session was refused a refresh because its holder is no longer admitted to the client.",
      "message": {
        "en": "{subject}'s session at {targets_0_id} was refused a refresh"
      }
    },
    "roster.session.revoked": {
      "summary": "A person's sessions were revoked.",
      "message": {
        "en": "{actor} revoked {subject}'s sessions, ending {data_ended, plural, one {#} other {#}}"
      }
    },
    "roster.slack_action.held": {
      "summary": "A change to a Slack workspace or channel is held, and needs an operator.",
      "message": {
        "en": "a change to {targets_0_id} is held: {outcome_reason}"
      }
    },
    "roster.slack_app.created": {
      "summary": "A catalogued Slack App was created.",
      "message": {
        "en": "{actor} created Slack App {targets_0_id} for workspace {targets_1_id}"
      }
    },
    "roster.slack_app.install_refused": {
      "summary": "An install of a catalogued Slack App was refused because it was made into another workspace.",
      "message": {
        "en": "{actor}'s install of Slack App {targets_0_id} for workspace {targets_1_id} was refused: {outcome_reason}"
      }
    },
    "roster.slack_app.installed": {
      "summary": "A catalogued Slack App was installed into its workspace.",
      "message": {
        "en": "{actor} installed Slack App {targets_0_id} into workspace {targets_1_id}"
      }
    },
    "roster.slack_channel.adopted": {
      "summary": "An existing Slack channel was adopted into management, by name.",
      "message": {
        "en": "{outcome, select, success {{targets_1_id} was adopted} other {Slack refused to let {targets_1_id} be adopted}}"
      }
    },
    "roster.slack_channel.archived": {
      "summary": "An operator archived a Slack channel when forgetting its console record.",
      "message": {
        "en": "{outcome, select, success {{actor} archived {targets_1_id} in {targets_0_id}} other {Slack refused to archive {targets_1_id}; archive it in Slack by hand}}"
      }
    },
    "roster.slack_channel.created": {
      "summary": "A Slack channel was created.",
      "message": {
        "en": "{outcome, select, success {{targets_1_id} was created} other {Slack refused to create {targets_1_id}}}"
      }
    },
    "roster.slack_console_channel.created": {
      "summary": "An ordinary Slack channel was put under management from the console.",
      "message": {
        "en": "{actor} put the Slack channel {targets_1_id} in {targets_0_id} under management ({data_mode}, fed by {data_sources} directory groups and {data_members} individual addresses)"
      }
    },
    "roster.slack_console_channel.deleted": {
      "summary": "A console-managed Slack channel's record was deleted from the console; the channel stays in Slack.",
      "message": {
        "en": "{actor} stopped managing the Slack channel {targets_1_id} in {targets_0_id}; the channel stays in Slack"
      }
    },
    "roster.slack_console_channel.updated": {
      "summary": "A console-managed Slack channel's record was changed from the console.",
      "message": {
        "en": "{actor} changed the managed Slack channel {targets_1_id} in {targets_0_id} ({data_changes})"
      }
    },
    "roster.slack_leaver.reported": {
      "summary": "A person gone from the directory is still an active Slack member; reported rather than acted on.",
      "message": {
        "en": "a leaver in {targets_0_id} was reported: {outcome_reason}"
      }
    },
    "roster.slack_member.invited": {
      "summary": "A person was invited to a Slack channel.",
      "message": {
        "en": "{outcome, select, success {{subject} was invited to {targets_1_id}} other {Slack refused to invite {subject} to {targets_1_id}}}"
      }
    },
    "roster.slack_member.removed": {
      "summary": "A person was removed from a private Slack channel.",
      "message": {
        "en": "{outcome, select, success {{subject} was removed from {targets_1_id}} other {Slack refused to remove {subject} from {targets_1_id}}}"
      }
    },
    "roster.slack_removals.confirmed": {
      "summary": "An operator confirmed a set of Slack removals that were held.",
      "message": {
        "en": "{actor} confirmed the removal of {data_affected} members from {targets_0_id}"
      }
    },
    "roster.slack_shared.accepted": {
      "summary": "A workspace accepted an invitation to a shared channel.",
      "message": {
        "en": "{outcome, select, success {{targets_1_id} accepted the shared channel {targets_2_id} from {targets_0_id}} other {{targets_1_id} could not accept the shared channel {targets_2_id} from {targets_0_id}}}"
      }
    },
    "roster.slack_shared.invited": {
      "summary": "A workspace's bot was invited to a shared channel.",
      "message": {
        "en": "a shared-channel invitation to {targets_1_id} for {targets_2_id} was sent by {targets_0_id}"
      }
    },
    "roster.slack_shared_channel.created": {
      "summary": "A Slack Connect channel was defined from the console.",
      "message": {
        "en": "{actor} defined the Slack Connect channel {targets_1_id}, hosted by {targets_0_id}, shared with {data_with}, fed by {data_sources} directory groups and {data_members} individual addresses"
      }
    },
    "roster.slack_shared_channel.deleted": {
      "summary": "A Slack Connect channel's definition was deleted from the console; the channel stays in Slack.",
      "message": {
        "en": "{actor} deleted the definition of the Slack Connect channel {targets_1_id}, hosted by {targets_0_id}; the channel stays in Slack"
      }
    },
    "roster.slack_shared_channel.updated": {
      "summary": "A Slack Connect channel's definition was changed from the console.",
      "message": {
        "en": "{actor} changed the Slack Connect channel {targets_1_id}, hosted by {targets_0_id} ({data_changes})"
      }
    },
    "roster.slack_workspace.connect_refused": {
      "summary": "An install of the roster's Slack App was refused because it was made into a workspace other than the one first connected.",
      "message": {
        "en": "{actor}'s install of the roster's Slack App for workspace {targets_0_id} was refused: {outcome_reason}"
      }
    },
    "roster.slack_workspace.connected": {
      "summary": "A Slack workspace was connected by installing the App.",
      "message": {
        "en": "{actor} connected Slack workspace {targets_0_id}"
      }
    },
    "roster.slack_workspace.disconnected": {
      "summary": "A Slack workspace was disconnected.",
      "message": {
        "en": "{actor} disconnected Slack workspace {targets_0_id}"
      }
    },
    "roster.slack_workspace.owner_changed": {
      "summary": "The directory that owns a Slack workspace was changed by the installation-wide operator.",
      "message": {
        "en": "{actor} changed the owner of Slack workspace {targets_0_id} from {data_from} to {data_to}"
      }
    },
    "roster.token.exchanged": {
      "summary": "A token was exchanged for one another client accepts, or the exchange was refused.",
      "message": {
        "en": "{outcome, select, success {{actor} exchanged a token for {targets_0_id}} denied {{actor} was refused a token for {targets_0_id}} other {{actor} could not exchange a token for {targets_0_id}}}"
      }
    },
    "roster.workspace.connected": {
      "summary": "A directory was connected.",
      "message": {
        "en": "{actor} connected directory {targets_0_id}"
      }
    },
    "roster.workspace.disconnected": {
      "summary": "A directory was disconnected.",
      "message": {
        "en": "{actor} disconnected directory {targets_0_id}"
      }
    },
    "roster.workspace.domains_changed": {
      "summary": "The domains a directory answers for changed.",
      "message": {
        "en": "{actor} changed the domains directory {targets_0_id} answers for"
      }
    },
    "roster.workspace.groups_changed": {
      "summary": "The groups served from a directory changed.",
      "message": {
        "en": "{actor} changed the groups served from directory {targets_0_id}, now {data_groups}"
      }
    },
    "roster.workspace.reconnected": {
      "summary": "A connected directory was given a new consent.",
      "message": {
        "en": "{actor} reconnected directory {targets_0_id}"
      }
    }
  }
}
