{{- /* Code generated by `just audit-config-schemas` from audit/profiles/*.yaml (min_preset). DO NOT EDIT. */ -}}
{{- define "audit.frameworkPresets" -}}
billing-nl: standard
dora: attested
evidence-etsi: attested
history: operational
nen-7513: attested
pci-dss: attested
security: standard
{{- end -}}
