// Code generated by `just sentences` from sdk/catalogue/common.yaml. DO NOT EDIT.
import type { Sentences } from "../sentences.js";

export const common: Sentences = {
  "source": "audit",
  "version": "2.2.0",
  "locales": [
    "en"
  ],
  "actions": {
    "audit.catalogue.registered": {
      "summary": "A source registered a catalogue version.",
      "message": {
        "en": "{actor} registered catalogue {targets_0_id}"
      }
    },
    "audit.clock.synchronised": {
      "summary": "The daily clock-synchronisation check ran.",
      "message": {
        "en": "clock on {observer_instance} synchronised with UTC, offset {data_offset_ms} ms"
      }
    },
    "audit.export.completed": {
      "summary": "An export job finished and its signed URL was issued.",
      "message": {
        "en": "export {targets_0_id} completed with {data_records} records"
      }
    },
    "audit.export.requested": {
      "summary": "An export job was started.",
      "message": {
        "en": "{actor} requested an export of the {profile} profile"
      }
    },
    "audit.facets": {
      "summary": "Facet counts were read for a profile.",
      "message": {
        "en": "{actor} read facets of the {profile} profile"
      }
    },
    "audit.get": {
      "summary": "One record was read by id.",
      "message": {
        "en": "{actor} read record {targets_0_id}"
      }
    },
    "audit.hold.placed": {
      "summary": "A legal hold was placed.",
      "message": {
        "en": "{actor} placed hold {targets_0_id}"
      }
    },
    "audit.hold.released": {
      "summary": "A legal hold was released.",
      "message": {
        "en": "{actor} released hold {targets_0_id}"
      }
    },
    "audit.key.destroyed": {
      "summary": "A pseudonymisation key was destroyed, unlinking its pseudonyms.",
      "message": {
        "en": "{actor} destroyed key {targets_0_id}"
      }
    },
    "audit.preset.changed": {
      "summary": "A preset version in use changed.",
      "message": {
        "en": "{actor} changed preset {targets_0_id}"
      }
    },
    "audit.profile.changed": {
      "summary": "A profile's composition or retention changed.",
      "message": {
        "en": "{actor} changed profile {targets_0_id}"
      }
    },
    "audit.pseudonym.resolved": {
      "summary": "A pseudonym was resolved back to the identity behind it.",
      "message": {
        "en": "{actor} resolved pseudonym {targets_0_id}"
      }
    },
    "audit.retention.extended": {
      "summary": "The lock on an object holding an earlier record was lengthened because a later record relies on it.",
      "message": {
        "en": "the lock on record {targets_0_id} was lengthened for record {targets_1_id}"
      }
    },
    "audit.seal.failed": {
      "summary": "Verification of the seals of an hour failed.",
      "message": {
        "en": "the seals of {targets_0_id} FAILED verification: {outcome_reason}"
      }
    },
    "audit.seal.verified": {
      "summary": "The seals of an hour were verified.",
      "message": {
        "en": "the seals of {targets_0_id} verified"
      }
    },
    "audit.seal.written": {
      "summary": "A seal was signed and written for an hour.",
      "message": {
        "en": "seal {targets_0_id} written covering {data_objects} objects"
      }
    },
    "audit.search": {
      "summary": "A search was executed against a profile.",
      "message": {
        "en": "{actor} searched the {profile} profile"
      }
    },
    "audit.writer.dead_lettered": {
      "summary": "A record could not be processed and was written to the dead-letter prefix.",
      "message": {
        "en": "record {targets_0_id} dead-lettered: {outcome_reason}"
      }
    },
    "audit.writer.started": {
      "summary": "A split writer instance started.",
      "message": {
        "en": "writer {observer_instance} started"
      }
    },
    "audit.writer.stopped": {
      "summary": "A split writer instance stopped.",
      "message": {
        "en": "writer {observer_instance} stopped"
      }
    }
  }
}
