package releasecheck

import (
	"bufio"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"go.yaml.in/yaml/v3"
)

var koPinRE = regexp.MustCompile(`-X github\.com/truvity/sluis/internal/version\.Module=(\S+)`)

// TestTheModuleImagesAreOnePerModuleEachPinnedToItsModule holds the ko images
// of .goreleaser.yaml to hack/release-zips.txt and hack/release-images.txt
// (the list the release workflow's attest-oci matrix and release-verify read),
// and writes the result as a golden: an image added, renamed or unpinned is a
// reviewed change, and none can be published without a signature.
func TestTheModuleImagesAreOnePerModuleEachPinnedToItsModule(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(root, ".goreleaser.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	var cfg struct {
		Kos []struct {
			ID           string   `yaml:"id"`
			Build        string   `yaml:"build"`
			Main         string   `yaml:"main"`
			Repositories []string `yaml:"repositories"`
			Ldflags      []string `yaml:"ldflags"`
			Platforms    []string `yaml:"platforms"`
			BaseImage    string   `yaml:"base_image"`
			SBOM         string   `yaml:"sbom"`
		} `yaml:"kos"`
	}
	if err = yaml.Unmarshal(raw, &cfg); err != nil {
		t.Fatal(err)
	}
	// hack/release-images.txt: the images it lists.
	f, err := os.Open(filepath.Join(root, "hack", "release-images.txt"))
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()
	listed := map[string]bool{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		if len(fields) == 2 && fields[0] == "image" {
			listed[fields[1]] = true
		}
	}
	var golden strings.Builder
	golden.WriteString("# image | module pin | platforms | base (generated by TestTheModuleImagesAreOnePerModuleEachPinnedToItsModule; UPDATE_GOLDEN=1 rewrites)\n")
	modules := map[string]bool{}
	for _, k := range cfg.Kos {
		if k.ID != "sluis" && !strings.HasPrefix(k.ID, "sluis-") {
			continue
		}
		ref := "ghcr.io/truvity/sluis/" + k.ID
		if !listed[ref] {
			t.Errorf("image %s is built but hack/release-images.txt does not list it: it would not be signed or attested", ref)
		}
		pin := ""
		for _, l := range k.Ldflags {
			if m := koPinRE.FindStringSubmatch(l); m != nil {
				pin = m[1]
			}
		}
		if k.ID != "sluis" {
			name := strings.TrimPrefix(k.ID, "sluis-")
			modules[name] = true
			if k.Main != "./cmd/sluis" {
				t.Errorf("image %s is built from %q, want ./cmd/sluis (the k8s main; the cmd/sluis-<module> mains are Lambda-only)", k.ID, k.Main)
			}
			if want := "sluis-module=" + name; pin != want {
				t.Errorf("image %s is pinned to %q, want %q: it would run as another module", k.ID, pin, want)
			}
			if len(k.Repositories) != 1 || !strings.HasSuffix(k.Repositories[0], "/"+k.ID) {
				t.Errorf("image %s: repositories %v do not end in /%s", k.ID, k.Repositories, k.ID)
			}
		} else if pin != "" || k.Build != "sluis" {
			t.Errorf("the sluis image is the unpinned multi-call build, got build %q pin %q", k.Build, pin)
		}
		if k.BaseImage != "gcr.io/distroless/static:nonroot" || k.SBOM != "none" || strings.Join(k.Platforms, ",") != "linux/amd64,linux/arm64" {
			t.Errorf("image %s: base %q sbom %q platforms %v differ from the sluis image's", k.ID, k.BaseImage, k.SBOM, k.Platforms)
		}
		golden.WriteString(ref + " | " + pin + " | " + strings.Join(k.Platforms, ",") + " | " + k.BaseImage + "\n")
	}
	// Every module with a zip has an image, and no image is for a module without one.
	for _, z := range releaseZips(t) {
		if z.kind == "module" && !modules[z.name] {
			t.Errorf("module %s has a Lambda zip and no container image", z.name)
		}
		delete(modules, z.name)
	}
	for m := range modules {
		t.Errorf("image sluis-%s is for a module with no entry in hack/release-zips.txt", m)
	}
	path := filepath.Join("testdata", "module-images.golden")
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		if err = os.WriteFile(path, []byte(golden.String()), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(want) != golden.String() {
		t.Errorf("the images changed; review and run UPDATE_GOLDEN=1 go test ./internal/releasecheck\n--- golden\n%s--- built from .goreleaser.yaml\n%s", want, golden.String())
	}
}
