package releasecheck

import (
	"bufio"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"go.yaml.in/yaml/v3"
)

// zipEntry is one line of hack/release-zips.txt.
type zipEntry struct{ kind, name string }

func releaseZips(t *testing.T) []zipEntry {
	t.Helper()
	f, err := os.Open(filepath.Join(root, "hack", "release-zips.txt"))
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	var out []zipEntry
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		if len(fields) == 0 || strings.HasPrefix(fields[0], "#") {
			continue
		}
		if len(fields) != 2 {
			t.Fatalf("release-zips.txt: %q is not `kind name`", sc.Text())
		}
		out = append(out, zipEntry{fields[0], fields[1]})
	}
	if len(out) < 3 {
		t.Fatalf("release-zips.txt lists %d zips: it read the wrong thing", len(out))
	}
	return out
}

type buildCfg struct {
	ID      string   `yaml:"id"`
	Main    string   `yaml:"main"`
	Binary  string   `yaml:"binary"`
	Goos    []string `yaml:"goos"`
	Goarch  []string `yaml:"goarch"`
	Tags    []string `yaml:"tags"`
	Ldflags []string `yaml:"ldflags"`
}

type zipArchive struct {
	ID      string   `yaml:"id"`
	IDs     []string `yaml:"ids"`
	Formats []string `yaml:"formats"`
	Name    string   `yaml:"name_template"`
}

var pinRE = regexp.MustCompile(`-X github\.com/truvity/sluis/internal/version\.Module=(\S+)`)

// TestTheLambdaZipsAreOnePerModuleEachPinnedToItsModule holds .goreleaser.yaml to
// hack/release-zips.txt (the list release-verify and the release workflow
// check the published assets against) and writes the result as a golden, so
// that a zip added, renamed or unpinned is a reviewed change.
func TestTheLambdaZipsAreOnePerModuleEachPinnedToItsModule(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(root, ".goreleaser.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	var cfg struct {
		Builds   []buildCfg   `yaml:"builds"`
		Archives []zipArchive `yaml:"archives"`
	}
	if err = yaml.Unmarshal(raw, &cfg); err != nil {
		t.Fatal(err)
	}
	var golden strings.Builder
	golden.WriteString("# name | build | main | pin | archive (generated by TestTheLambdaZipsAreOnePerModuleEachPinnedToItsModule; UPDATE_GOLDEN=1 rewrites)\n")
	zips := 0
	for _, a := range cfg.Archives {
		if len(a.Formats) != 1 || a.Formats[0] != "zip" || len(a.IDs) != 1 || !strings.HasPrefix(a.Name, "sluis-") {
			continue
		}
		zips++
		// A Lambda zip archive: its build must be a listed zip's.
		var entry *zipEntry
		for _, z := range releaseZips(t) {
			if a.Name == "sluis-"+z.name+"_{{ .Version }}_{{ .Os }}_{{ .Arch }}" {
				entry = &z
			}
		}
		if entry == nil {
			t.Errorf("archive %s (%s) is a Lambda zip that hack/release-zips.txt does not list", a.ID, a.Name)
			continue
		}
		var b *buildCfg
		for i := range cfg.Builds {
			if cfg.Builds[i].ID == a.IDs[0] {
				b = &cfg.Builds[i]
			}
		}
		if b == nil {
			t.Errorf("archive %s: no build %q", a.ID, a.IDs[0])
			continue
		}
		pin := ""
		for _, l := range b.Ldflags {
			if m := pinRE.FindStringSubmatch(l); m != nil {
				pin = m[1]
			}
		}
		switch entry.kind {
		case "module":
			if want := "./cmd/sluis-" + entry.name; b.Main != want {
				t.Errorf("zip %s is built from %s, want %s", entry.name, b.Main, want)
			}
			if want := "sluis-module=" + entry.name; pin != want {
				t.Errorf("zip %s is pinned to %q, want %q: it would run as another module", entry.name, pin, want)
			}
		case "legacy":
			if pin != "" {
				t.Errorf("the legacy zip %s is pinned to %q: it carries several modules and must not be", entry.name, pin)
			}
		}
		if b.Binary != "bootstrap" || len(b.Goos) != 1 || b.Goos[0] != "linux" || len(b.Goarch) != 1 || b.Goarch[0] != "arm64" {
			t.Errorf("build %s: the Lambda zip is one linux/arm64 `bootstrap`, got %s %v %v", b.ID, b.Binary, b.Goos, b.Goarch)
		}
		if !strings.Contains(strings.Join(b.Tags, ","), "lambda") {
			t.Errorf("build %s has no lambda tag: it would carry the Kubernetes storage", b.ID)
		}
		golden.WriteString("sluis-" + entry.name + "_<version>_linux_arm64.zip | " + b.ID + " | " + b.Main + " | " + pin + " | " + a.ID + "\n")
	}
	// Every listed zip has an archive: the list is not ahead of the config.
	if want := len(releaseZips(t)); zips != want {
		t.Errorf(".goreleaser.yaml builds %d Lambda zips, hack/release-zips.txt lists %d", zips, want)
	}
	// No signer zip or binary: the signer runs inside sluis-issuer.
	for _, z := range releaseZips(t) {
		if z.name == "signer" {
			t.Error("hack/release-zips.txt lists a signer zip: the signer runs inside sluis-issuer")
		}
	}
	path := filepath.Join("testdata", "lambda-zips.golden")
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		if err := os.WriteFile(path, []byte(golden.String()), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(want) != golden.String() {
		t.Errorf("the Lambda zips changed; review and run UPDATE_GOLDEN=1 go test ./internal/releasecheck\n--- golden\n%s--- built from .goreleaser.yaml\n%s", want, golden.String())
	}
}

// TestReleaseVerifyTestRuns keeps the fixture of
// hack/test-release-verify.sh at the list: a zip added to release-zips.txt and
// not to the fixture would make the script fail, so the script is run here.
func TestReleaseVerifyTestRuns(t *testing.T) {
	if ok, out := run(t, "test-release-verify.sh"); !ok {
		t.Fatalf("hack/test-release-verify.sh failed:\n%s", out)
	}
}
